POST http://localhost:5000/api/Temperature HTTP/1.1
content-type: application/json

{
    "temperature": 28,
    "humidity": 123.2,
    "timestamp": "Tue, 15 Nov 1994 12:45:26 GMT"
}

### FAIL
POST http://localhost:5000/api/Temperature HTTP/1.1
content-type: application/json

{
    "temperature": 321.1,
    "humidity": 123.2,
    "timestamp": 1111
}

### Low temp, must trigger notifications
POST http://localhost:5000/api/Temperature HTTP/1.1
content-type: application/json

{
    "temperature": 8,
    "humidity": 123.2,
    "timestamp": "Tue, 15 Nov 1994 12:45:26 GMT"
}

###
POST http://displayhometemp.herokuapp.com/api/Temperature HTTP/1.1
content-type: application/json

{
    "temperature": 8,
    "humidity": 123.2,
    "timestamp": "Tue, 15 Nov 1994 12:45:26 GMT"
}

###
POST http://displayhometemp.herokuapp.com/api/webPush/testNotify HTTP/1.1
Content-Type: application/json

{
    "vapidprivatekey": "K3fW8O8T3sIxJjVadzw8GQzy5sZkeo4iQnNRn16o10E"
}