POST http://localhost:5000/api/Temperature HTTP/1.1
content-type: application/json

{
    "temperature": 321.1,
    "humidity": 123.2,
    "timestamp": "Tue, 15 Nov 1994 12:45:26 GMT"
}

### FAIL
POST http://localhost:5000/api/Temperature HTTP/1.1
content-type: application/json

{
    "temperature": 321.1,
    "humidity": 123.2,
    "timestamp": 1111
}