CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Temps" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Temp" double precision NOT NULL,
    "Humidity" double precision NOT NULL,
    "Time" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Temps" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210106080423_Init', '5.0.1');

COMMIT;